### PR TITLE
Wait until the user has finished making changes before refreshing.

### PR DESCRIPTION
**Pull request by chymb**
Hi,
One thing I've had complaints about is that it is very hard to make changes when using the Updates tab as it refreshes after each click, so I've attempted to put a delay in.
I initially had a 5 second delay but figured that was too long, so I've settled on 1.5, though I'd be interested to get others' thoughts.
Cheers,
Chris

### CODE REVIEW

**Comment by gregneagle** [comment]
I assume you are referring to what happened when you add or remove "Other available updates" in the Updates view.

See https://github.com/munki/munki/issues/334 for a discussion of the issue.

I'll try testing this proposed change to see how it "feels".

**Comment by gregneagle** [comment]
I tried it. I don't think it works as I'd expect.

I think a better approach would be each time one clicks a + or x in the updates view, a timer is started. New clicks reset the timer. Once the timer expires, the update check is started. As long as people are making changes within the timer window, the timer doesn't expire.

**Comment by erikng** [comment]
I would like this change.

**Comment by chymb** [comment]
Yes, that's the issue #334. Sorry, it didn't occur to me to check for one.
The approach you described it is what it's supposed to be doing. Perhaps the timeout of 1.5s is not long enough to feel right.

**Comment by gregneagle** [comment]
The observed behavior is that after the first click of a + or x I can continue to make other "choices" for an additional 1.5 seconds, and then the update check starts.

**Comment by chymb** [comment]
Hi Greg,
I've amended that commit (is that bad practice?) so that the incrementation of the _pending_update counter happens before the CSS transition. I also increased the time-out to 3.5 seconds, which feels a bit better to me.
Let me know what you think.

**Comment by gregneagle** [comment]
I don't see a significant difference in behavior. I make a change, then another, and then the update check starts.

**Comment by chymb** [comment]
Hi Greg,
Sorry for the delay in getting back to this. It looks like the delay is not honoured if the MunkiItems.updateCheckNeeded() is not true, so I've taken that check out.
I initially created a "dontCheckForUpdatesAfterDelay" function but that then involved tracking the changes that had been queued to that point so that updateCheckNeeded was accurate and it seemed like a more complicated change for little benefit.
Let me know how it goes.
Cheers,
Chris

**Comment by gregneagle** [comment]
Closing this old PR, which would need to be completely re-done for the new MSC.app written in Swift. This does not mean the issue has been resolved; just that this PR is unlikely to be useful

**Pull request closed without merging**
