### PR TITLE
Opt-in behavior to ignore system proxies.

### LINKED ISSUE #646: Add preference to bypass system proxy
I'd like for my Munki clients to ignore system proxy settings and connect directly to my Simian server.

This should be a straightforward change since [gurl.py](https://github.com/munki/munki/blob/master/code/client/munkilib/gurl.py) is using NSURLSession:

```
from CFNetwork import kCFNetworkProxiesHTTPSEnable
[...]
configuration.setConnectionProxyDictionary_({ kCFNetworkProxiesHTTPSEnable: False })
```

I suspect many (most?) people won't want this configuration though, and would prefer their munki connections go through the (managed) proxy, so I propose exposing a default-off flag ("NoProxy", perhaps?) in [ManagedInstalls.plist](https://github.com/munki/munki/blob/master/Preferences/ManagedInstalls.plist). 

Let me know if this change sounds good and I'll send a PR.

### PR DESCRIPTION
**Pull request by verycarefully**
Fix #646

### CODE REVIEW

**Comment by gregneagle** [comment]
This looks good; I won't merge until after the 2.8.0 release, which (knock on wood) should happen later this week.

**Comment by gregneagle** [comment]
In the meantime, could you address the linting/PEP-8 errors noted here: https://travis-ci.org/munki/munki/builds/150682883

**Comment by gregneagle** [comment]
It occurs to me that we'll want to document that this feature only works on OS versions that support NSURLSession, that is 10.9+.

**Comment by natewalck** [comment]
As for the lint errors, you can run them manually by following these directions:

https://github.com/munki/munki/tree/master/tests#getting-started

That is the exact script that runs in travis CI, so you'll know if it is happy or not.

**Comment by gregneagle** [comment]
@verycarefully Can you please add documentation for this new feature to the wiki?

**Comment by verycarefully** [comment]
Done: appended an entry to https://github.com/munki/munki/wiki/Preferences

Thanks!

**Pull request merged**
