### PR TITLE
Add support for icon_hash

### PR DESCRIPTION
**Pull request by bochoven**
A rewrite of #425 which uses the xattr attribute com.googlecode.munki.sha256 to store the current hash. 

Check for the addition of an icon_hash key in a package plist. If the key is present and matches a hash of the corresponding icon that has already been downloaded, no attempt will be made to download the icon/verify the icon with the server. If the icon_hash is not present or the hash does not match the standard procedure for checking icons will be followed.

### CODE REVIEW

**Comment by bochoven** [comment]
bump

**Comment by gregneagle** [comment]
I really wish Ed E would weigh in: seems he has disappeared.

**Comment by bochoven** [comment]
Ok, thought you were holding off until I added hash generation in munkiimport..

**Comment by gregneagle** [comment]
Adding hash generation would be appreciated; seems like that would take a few minutes at most to implement.

**Comment by bochoven** [comment]
Writing the hashing code is simple, but knowing where to put it is hard...

**Comment by bochoven** [comment]
Issue has been addressed by #425

**Pull request closed without merging**
