### PR TITLE
Minor changes at "Managed Software Center" and "munki-notifier" spanish localization

### PR DESCRIPTION
**Pull request by LcTrKiD**
Minor changes at "Managed Software Center" and "munki-notifier" localization

### CODE REVIEW

**Comment by gregneagle** [comment]
Thank you. I'll have to wait for confirmation of a CLA from you before I can merge this.

**Comment by gregneagle** [comment]
BTW, as for the items that are not new to Munki3: some of the Spanish terms have been changed a few times -- it's hard for me to know why, but I have to imagine some different dialects (like Spanish spoken in Mexico or other Latin American countries vs parts of Spain?)

**Comment by LcTrKiD** [comment]
I can talk with Noel (the other translator) to keep the localization as inmutable as possible. I tried to use the more neutral term that is “ítem”.

**Comment by LcTrKiD** [comment]
can you send me the CLA?

**Comment by gregneagle** [comment]
That would be appreciated. I don't want translations that go back and forth depending on who looked at it last.

**Comment by clburlison** [comment]
https://github.com/munki/munki/wiki/Contributing-to-Munki

**Comment by gregneagle** [comment]
...which links to https://disney-animation.s3.amazonaws.com/uploads/production/open_source_pdf/2/pdf/TestCLA-1.pdf. Note: do not send the completed CLA to _me_. Follow the directions here: https://github.com/munki/munki/wiki/Contributing-to-Munki

**Comment by LcTrKiD** [comment]
done!

**Comment by gregneagle** [comment]
CLA received. Let me know if you hear from @nbalonso.

**Comment by LcTrKiD** [comment]
I’ve already talked with @nbalonso via twitter. Everything is fine about the recent changes in the localization.

**Comment by gregneagle** [comment]
Thanks!

**Pull request merged**
