### PR TITLE
option for munkiimport --configure to not open pkginfo file after import.  

### PR DESCRIPTION
**Pull request by weswhet**
I was intrigued by https://github.com/munki/munki/pull/588.

Tried to keep it as simple as possible.

### CODE REVIEW

**Comment by keeleysam** [comment]
This should be a Boolean, not a string.  Otherwise looks fine to me.

On Sunday, April 10, 2016, Wesley Whetstone <notifications@github.com>
wrote:

> I was intrigued by #588 <https://github.com/munki/munki/pull/588>.
>
> Tried to keep it as simple as possible.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/munki/munki/pull/591
> Commit Summary
>
>    - adding in an option for munkiimport --configure to prompt to open
>    the pkginfo file after import
>
> File Changes
>
>    - *M* code/client/munkiimport
>    <https://github.com/munki/munki/pull/591/files#diff-0> (7)
>
> Patch Links:
>
>    - https://github.com/munki/munki/pull/591.patch
>    - https://github.com/munki/munki/pull/591.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/munki/munki/pull/591>
>


-- 
Samuel Keeley

**Comment by weswhet** [comment]
@keeleysam I agree. By default configure() writes everything out as a string though. Tried to go for as little changes as possible.

**Comment by gregneagle** [comment]
Perhaps even fewer changes and no new preference: if you set the text editor to an empty string (or the preference is undefined -- the pkginfo is not opened in an editor.

**Comment by weswhet** [comment]
Noted this feature here... https://github.com/munki/munki/wiki/munkiimport#extras

**Comment by gregneagle** [comment]
I don't think we need to do anything at all other than update some documentation and prompt text.

If you set the editor to an empty string (or delete the key entirely) munkiimport won't open the pkginfo in a text editor.

**Comment by gregneagle** [comment]
See also https://github.com/munki/munki/commit/51f6c7a58f2c3ca6c39234c13b647a9790689de5

**Pull request closed without merging**
