### PR TITLE
Change to detecting laptop/desktop by identifying if the system has a battery

### PR DESCRIPTION
**Pull request by jamesez**
primary author: @gregneagle, via Slack

### CODE REVIEW

**Comment by gregneagle** [comment]
I'm going to be perhaps a bit arbitrary and ask that the function be moved to `powermgr.py` where it can take advantage of some existing NSBundle function definitions (the function is really just a simplified version of `getBatteryPercentage()`) and also perhaps be renamed `hasInternalBattery()` to reflect that it won't be confused by external (UPS) batteries.

**Comment by gregneagle** [comment]
I also wonder if there's any logic in Managed Software Center that needs to be updated.

**Comment by gregneagle** [comment]
(I did a quick search and I _think_ no changes are needed in Managed Software Center)

**Comment by jamesez** [comment]
I also can't find any other laptop/desktop detection code in the entire repo, so I think MSC.app is clear.

**Pull request merged**
