### PR TITLE
LastRunWithNoErrors

### PR DESCRIPTION
**Pull request by mikedodge04**
LastSuccessfulRun to ManagedInstallReport

$ cat /Library/Managed\ Installs/ManagedInstallReport.plist |grep Last -A1
	<key>LastSuccessfulRun</key>
	<string>2017-08-10 20:34:20 +0000</string>

### CODE REVIEW

**Comment by gregneagle** [comment]
Two things:

1) A new feature should go into Munki3dev and not master

2) Your definition of "LastSuccessfulRun" might not match others' definitions. What problem are you trying to solve with this that isn't solved with a reporting console like Sal or MunkiReport or similar?

**Comment by gregneagle** [comment]
one more thing:

If there are errors in this run, then LastSuccessfulRun is not set. Does this value get copied over from a previous run, then?

**Comment by gregneagle** [comment]
(my point about your definition of "LastSuccessfulRun": you could have a bogus item in a manifest that caused an error every run because Munki could not find Foo in any available catalogs. Yet it successfully installs many other items, maybe for weeks. What useful/actionable info is given by setting LastSuccessfulRun?

**Comment by mikedodge04** [comment]
I want a way to understand client side whether munki is in a good state. If LastSuccessfulRun is > 30days. I plan on forgetting the pkgs and reinstalling.

**Comment by gregneagle** [comment]
You plan on forgetting what packages and reinstalling what?

**Comment by mikedodge04** [comment]
all munki pkgs, and my local manifest :)

**Comment by gregneagle** [comment]
That seems awfully Facebook-specific. Rarely are errors during a Munki run resolved by reinstalling the Munki packages on the client: they are almost always caused by server-side issues with a manifest or catalog items.

I think this key/value will cause a lot of confusion for most Munki admins.

You could do this for yourself with no code changes to Munki in a Munki postflight script.

**Comment by gregneagle** [comment]
(also note the conflicts; you'll need to fix the PR in any case)

**Comment by mikedodge04** [comment]
LastSuccessfulRun is still correct though. Would you be ok if we changed the key name? I want to update my opensource cpe_munki cookbook to have an remediate flag.

**Comment by gregneagle** [comment]
Change the key name to LastRunWithNoErrors or something similar. "LastSuccessfulRun" to too open to individual admin opinion.

**Comment by gregneagle** [comment]
As the "First-time contributor" badge reminded me: I need you to submit a CLA:
https://github.com/munki/munki/wiki/Contributing-to-Munki

**Comment by mikedodge04** [comment]
/Library/Preferences/ManagedInstalls LastCheckDate instead

**Comment by gregneagle** [comment]
...wondering why you reopened this, and when you'll be covered by the CLA...

**Comment by mikedodge04** [comment]
My people are working on that as we speak :)  @natewalck  asked me to open it again

**Pull request closed without merging**
