### PR TITLE
Directly create layout constraints

### PR DESCRIPTION
**Pull request by jamesez**
Fixes issue #1022 where the autoresizing masks occasionally end up pinning the webView to its smallest size.

### CODE REVIEW

**Comment by gregneagle** [comment]
I'll freely admit I do not understand layout constraints at all, but this looks reasonable...

**Comment by gregneagle** [comment]
One new issue with this change is that using the Web Inspector to debug the HTML/CSS/Javascript parts of MSC is now partially broken. To see this, `defaults write com.googlecode.munki.ManagedSoftwareCenter developerExtrasEnabled -bool YES`
Then control-click anywhere in the webview and choose "Inspect Element".

**Comment by jamesez** [comment]
Okay, I'll look at that tomorrow; out of brain after cranking on this for the last 5+ hours.

**Comment by gregneagle** [comment]
No worries. Your help so far is greatly appreciated.

**Comment by jamesez** [comment]
Yuck! I honestly never used the inspector there before today, so I didn't check.

I tinkered around with a few dead ends this morning, but the thing that seems to be working is to have a view controller manage the webview; that way, when the inspector tries to jam itself into the view hierarchy everything lines up correctly. I want to make sure I didn't introduce a race condition against a nil view before I'm going to push the patch.

Back at it after breakfast.

**Comment by gregneagle** [comment]
I wonder if everything would be simpler if the top-level view was an NSSplitView, with the sidebar and webview as children of the NSSplitView.

**Comment by gregneagle** [comment]
After some quick experiments, I think using NSSplitView seems promising. I can even go back to using the autoresizing mask and not have to manually create layout restraints.

**Comment by gregneagle** [comment]
Even easier/better, since we don't need to resize the two views, seems to be to just have a superview contain the web view. Currently, the webview's superview is the window view; instead it should be a custom NSView with the correct position and autoresize mask...

**Comment by gregneagle** [comment]
This branch: https://github.com/munki/munki/tree/msc-layout-test resolves the issues with the web inspector, and I have not yet seen the layout issue on Big Sur. Please give it a whirl.

**Comment by jamesez** [comment]
I've updated this branch to build out a View Controller, instead, if you want to try it.

**Pull request merged**
