### PR TITLE
manifestutil: expand-included-manifests

### PR DESCRIPTION
**Pull request by cwindus**
Per FR https://github.com/munki/munki/issues/663 sans indented output.

### CODE REVIEW

**Comment by gregneagle** [comment]
Evaluation of all PRs are on hold until after the 2.8.1 official release, but I'll look at this soon after.

**Comment by gregneagle** [comment]
Take at look at this commit: https://github.com/munki/munki/commit/a8fb9feedede7ca52e01694931c8eecae83ff8f1

I've attempted the recursive, indented printing of included manifests. I'm not sure I like it, though

**Comment by gregneagle** [comment]
@cwindus ^^^

**Comment by cwindus** [comment]
@gregneagle Oh man, incredibly sorry, I haven't signed in for a long time. Will check this out as soon as I get back from holidays.

**Pull request merged**
