### PR TITLE
Add serial number to README.md

### PR DESCRIPTION
**Pull request by bochoven**

### CODE REVIEW

**Comment by gregneagle** [comment]
I forgot that directory and files even existed. I wonder if it might be better to just delete the entire folder to eliminate duplicate work between the wiki and the README in the Preferences folder. (This folder pre-dates the wiki and was intended as a bit of "getting started" information.

**Comment by bochoven** [comment]
Yes, delete it if you want. I was just making sure there aren't different 'truths' about Munki's behaviour.

**Comment by bochoven** [comment]
I think the low barrier of updating the wiki weighs up against the practice of having documentation following releases.

**Comment by gregneagle** [comment]
Removed Preferences directory here: https://github.com/munki/munki/commit/81160a1741efaa4ed16f124860cfb32e6ae8a00a

**Pull request closed without merging**
