### PR TITLE
60 second network wait

### PR DESCRIPTION
**Pull request by erikng**
Help with very large networks.

### CODE REVIEW

**Comment by erikng** [comment]
Greg, as discussed.

Can you merge please?

**Comment by gregneagle** [comment]
I'm going to merge this, but when you come back and ask it to be bumped to 300 seconds, I'm just going to tell you to fork...

**Comment by erikng** [comment]
I won't do it again. :)

**Comment by gregneagle** [comment]
That's what you said last time.

**Comment by erikng** [comment]
That was before I had an image on the outside ring. I have another contingency in place as well if it takes longer than 60 seconds but I highly doubt it will be needed now with this being merged. 

Thanks.

**Pull request merged**
