### PR TITLE
Authrestart improvements

### PR DESCRIPTION
**Pull request by weswhet**
Better handling of machines 10.6 - 10.12.
More Thorough/Accurate Logging.

### CODE REVIEW

**Comment by keeleysam** [comment]
Perhaps this should use `fdesetup authrestart -delayminutes -1` on Sierra and later so that reporting can run and then reboot via normal methods.

**Comment by weswhet** [comment]
@keeleysam I've tested the proposed changes locally but when `doRestart()` is called the reporting and post flight scripts have already run. I don't think it's necessary.

**Comment by gregneagle** [comment]
I agree that it is not needed and just adds additional complexity.

**Comment by keeleysam** [comment]
Ahh right, got that confused with the bit about reports after apple updates.

**Comment by weswhet** [comment]
any other thoughts on this guy?

**Comment by weswhet** [comment]
@gregneagle any concerns for this?

**Comment by gregneagle** [comment]
Was going to look at it again after the 2.8.1 release, but then people started reporting issues with the 2.8.1 release on older versions of OS X, so now maybe after the 2.8.2 release...

**Comment by weswhet** [comment]
Just an FYI but I just sent in my signed CLA.

**Comment by gregneagle** [comment]
Receipt confirmed.

**Comment by gregneagle** [comment]
I will merge this to master today -- but then need documentation written ASAP. Agreed?

**Comment by gregneagle** [comment]
Additionally, I'd like to start a discussion about how to securely implement a way for MSC.app to ask for credentials to set up authrestart when an update requires a restart.

**Comment by erikng** [comment]
That would be amazing.

On Nov 22, 2016, at 10:27 AM, Greg Neagle <notifications@github.com<mailto:notifications@github.com>> wrote:


Additionally, I'd like to start a discussion about how to securely implement a way for MSC.app to ask for credentials to set up authrestart when an update requires a restart.

-

**Comment by gregneagle** [comment]
@weswhet : Will you write documentation if I merge this?

**Comment by weswhet** [comment]
@gregneagle most certainly.

**Comment by gregneagle** [comment]
@weswhet : Get writing!

**Comment by weswhet** [comment]
starter doc https://github.com/munki/munki/wiki/Authorized-Restarts, also updated https://github.com/munki/munki/wiki/Preferences

**Pull request merged**
