### PR TITLE
Add munki3 logic to make_munki_mpkg_dep.sh

### PR DESCRIPTION
**Pull request by erikng**
-Also remove whitespace from make_munki_mpkg.sh

### CODE REVIEW

**Comment by erikng** [comment]
Hold off on this one. I noticed something in the build packages that you changed. I'm going to have to add some additional logic.

**Comment by gregneagle** [comment]
Interesting. Here's the contents of the last notification I got from GitHub:

> Hold off on this one. I noticed something in the build packages that you changed. I'm going to have to add some additional logic.

So I've been holding off...

**Comment by erikng** [comment]
The only reason I ask is they are both launchdaemons.

**Comment by gregneagle** [comment]
...that do different things. One can unload/reload the app_usage_monitor (and even Munki can do it) without killing a managedsoftwareupdate session.

**Pull request merged**
