### PR TITLE
Fixed repoclean sorting by LooseVersion in reverse mode

### PR DESCRIPTION
**Pull request by LcTrKiD**
Tested with python 3.7.3 and system python in 10.14.5

### CODE REVIEW

**Comment by gregneagle** [comment]
Did you also test in Python 2.7?

**Comment by gregneagle** [comment]
There are a lot of unrelated code-formatting changes in the PR, which makes review take longer.

**Comment by LcTrKiD** [comment]
Yes, I used pipenv to generate an env with python 3.7.3 to test Python3 and /usr/bin/python to test Python2. Let me remove those changes and I'll make another PR

**Comment by gregneagle** [comment]
The formatting changes are fine, but probably should be a separate commit.

**Comment by gregneagle** [comment]
Thanks! I've made this error a few other times when converting from Python 2 to Python 3 and replacing the sorting custom functions...

**Pull request merged**
