### PR TITLE
Add Mojave SUS catalog to list of default catalogs.

### PR DESCRIPTION
**Pull request by dcoobs**
#861

### CODE REVIEW

**Comment by gregneagle** [comment]
https://github.com/munki/munki/wiki/Contributing-to-Munki

**Comment by dcoobs** [comment]
CLA signed and submitted

**Comment by gregneagle** [comment]
Thank you. In the interest of speed and efficiency I've just made the equivalent change myself here: https://github.com/munki/munki/commit/611050eb38b8089a17ec2450d89fabe3e6e31bd5

**Comment by erikng** [comment]
Ouch.

Thanks,
Erik Gomez
________________________________

**Pull request closed without merging**
