### PR TITLE
adding --skip-pkgs flag

### PR DESCRIPTION
**Pull request by midsandhighs**
This PR adds a `--skip-pkgs` option to the **repoclean** command, as a solution to [Issue#991](https://github.com/munki/munki/issues/991).

It adds an `if` statement to the `find_cleanup_items` function of the `RepoCleaner` class to loop through and add the _pkgpath_ and _uninstallpkgpath_ keys in **pkginfodb** to the `self.pkgs_to_keep` set while leaving the associated .pkginfo items in the `self.items_to_delete` list. 

Any feedback is welcome and appreciated.

### CODE REVIEW

**Comment by gregneagle** [comment]
How would doing this interact with "orphaned packages"? I'd think it would _create_ them...

Also, wondering why you don't just skip the pkg deleting section in this function if  `--skip-pkgs` is given instead of creating a  potentially huge structure containing the paths to a lot of packages to not delete.

**Comment by gregneagle** [comment]
Ping.

**Comment by midsandhighs** [comment]
Apologies for the long delay in response on this. 

I'm going to migrate it back to a _Draft_ so that I can update my fork to the latest release. My organization no longer hosts their own `munki` repository so I need to recreate the environment to test the changes against and perform debugging on the contents of `self.items_to_delete` & `self.pkgs_to_keep` to see if there is a more efficient way to handle the scenario listed in #991 

My understanding is there would be some process or worker external to `repoclean` performing the removal of the actual .pkg files but "orphaned packages" is not something I had factored into my code change. 

Thank you for your feedback and your time! 😄

**Comment by gregneagle** [comment]
Are you still working on this?

**Comment by gregneagle** [comment]
Closing. Please create a new PR if you resume work on this.

**Pull request closed without merging**
